# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Sparse"
license = "MIT"
licenselink = "https://github.com/jpiedra/hugo-sparse/blob/master/LICENSE.md"
description = "Simple theme with flat UI, solid color blocks and dropshadows"
homepage = "https://github.com/jpiedra/hugo-sparse/"
tags = ["flat", "shadows", "sparse"]
# features = ["", ""]
min_version = 0.17

[author]
  name = "Jonathan Piedra"
  homepage = "jpiedra.github.io"
